# Generated by Django 3.0.4 on 2020-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
